trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'AzureWebAppConnection'
  webAppName: 'your-webapp-name'                  
  resourceGroupName: 'your-resource-group'       
  packagePath: '$(Build.SourcesDirectory)/wwwroot'

steps:
 
  - task: Checkout@1

 
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(packagePath)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/site.zip'
      replaceExistingArchive: true


  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      appName: '$(webAppName)'
      resourceGroupName: '$(resourceGroupName)'
      package: '$(Build.ArtifactStagingDirectory)/site.zip'
trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'AzureWebAppConnection'  
  webAppName: 'your-webapp-name'                   
  resourceGroupName: 'your-resource-group'        
  packagePath: '$(Build.SourcesDirectory)/wwwroot' 

steps:
  - task: Checkout@1
  
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(packagePath)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/site.zip'
      replaceExistingArchive: true
      
  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      appName: '$(webAppName)'
      resourceGroupName: '$(resourceGroupName)'
      package: '$(Build.ArtifactStagingDirectory)/site.zip'
