trigger:
  branches:
    include:
      - main   # change if your branch is different

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'AzureWebAppConnection'  # your service connection name
  webAppName: 'your-webapp-name'                   # your Azure Web App name
  resourceGroupName: 'your-resource-group'        # your resource group name
  packagePath: '$(Build.SourcesDirectory)/wwwroot' # points to your wwwroot folder

steps:
  # 1?? Checkout repository
  - task: Checkout@1

  # 2?? Zip the site
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(packagePath)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/site.zip'
      replaceExistingArchive: true

  # 3?? Deploy to Azure Web App
  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      appName: '$(webAppName)'
      resourceGroupName: '$(resourceGroupName)'
      package: '$(Build.ArtifactStagingDirectory)/site.zip'
trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'AzureWebAppConnection'  
  webAppName: 'your-webapp-name'                   
  resourceGroupName: 'your-resource-group'        
  packagePath: '$(Build.SourcesDirectory)/wwwroot' 

steps:
  - task: Checkout@1
  
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(packagePath)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/site.zip'
      replaceExistingArchive: true
      
  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      appName: '$(webAppName)'
      resourceGroupName: '$(resourceGroupName)'
      package: '$(Build.ArtifactStagingDirectory)/site.zip'
